name: Firebase Actions

on:
  push:
    branches:
      - main

jobs:
  firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables for Firebase
        env:
          VITE_API_KEY: ${{ secrets.VITE_FIRESTORE_API_KEY }}
          VITE_APP_ID: ${{ secrets.VITE_FIRESTORE_APP_ID }}
          VITE_AUTH_DOMAIN: ${{ secrets.VITE_FIRESTORE_AUTH_DOMAIN }}
          VITE_BUCKET: ${{ secrets.VITE_FIRESTORE_STORAGE_BUCKET }}
          VITE_ID: ${{ secrets.VITE_FIRESTORE_PROJECT_ID }}
          VITE_MEASUREMENT_ID: ${{ secrets.VITE_FIRESTORE_MEASUREMENT_ID }}
          VITE_SENDER_ID: ${{ secrets.VITE_FIRESTORE_MESSAGING_SENDER_ID }}
        run: echo "Secrets have been loaded"
