name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Set environment variables for Firebase
        env:
          VITE_FIRESTORE_API_KEY: ${{secrets.VITE_FIRESTORE_API_KEY}}
          VITE_FIRESTORE_APP_ID: ${{secrets.VITE_FIRESTORE_APP_ID}}
          VITE_FIRESTORE_AUTH_DOMAIN: ${{secrets.VITE_FIRESTORE_AUTH_DOMAIN}}
          VITE_FIRESTORE_STORAGE_BUCKET: ${{secrets.VITE_FIRESTORE_STORAGE_BUCKET}}
          VITE_FIRESTORE_PROJECT_ID: ${{secrets.VITE_FIRESTORE_PROJECT_ID}}
          VITE_FIRESTORE_MEASUREMENT_ID: ${{secrets.VITE_FIRESTORE_MEASUREMENT_ID}}
          VITE_FIRESTORE_MESSAGING_SENDER_ID: ${{secrets.VITE_FIRESTORE_MESSAGING_SENDER_ID}}

        run: echo "Secrets have been loaded"

      - name: Install dependencies
        run: npm install

      - name: Build app with env variables
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
